### ISSUE TITLE
_includePaths is not iterable in Meteor 1.8

### ISSUE THREAD

**Issue by derwaldgeist** [Meteor-Community-Packages/meteor-scss#289]
- [ ] Feature request
- [x] Bug report
- [ ] Question

`meteor` version: 1.8.0.2
`fourseven:scss` version: 4.10.0

I'm trying to reference a stylesheet in the `reywood:bootstrap3-sass` package. This worked in my apps running on previous versions, but with Meteor 1.8.0.2, when I try this:

```scss
@import '{reywood:bootstrap3-sass}/assets/stylesheets/bootstrap/variables';
```

I get this error message:
```
 While processing files with fourseven:scss (for target web.browser.legacy):
   /client/stylesheets/main.scss: Scss compiler error: Error: _includePaths is not iterable
   on line 12 of globals
   from line 3 of {}/client/stylesheets/main.scss
   >> @import '{reywood:bootstrap3-sass}/assets/stylesheets/bootstrap/variables';
   
   --------^
```

This does not seem to be related to https://github.com/Meteor-Community-Packages/meteor-scss/issues/273, since my SCSS files are located in a Meteor package, not in an NPM package.

**Comment by ajsingh4** [comment]
Coming across the same issue but with Meteor 1.8.1.

**Comment by Philip-Nunoo** [comment]
Same Issue

**Comment by RTSchriner** [comment]
Anyone find a fix for this?

**Comment by sebakerckhof** [comment]
Do you guys have a scss-config.json file?

**Comment by ajsingh4** [comment]
I was trying to reference a path that did not exist for an import. Once I fixed that, that solved it.

**Comment by nikhilgoswami** [comment]
Correct answer as of Meteor 1.8 is
in terminal
cd import folder in project root
ln -s ../node_modules/bootstrap-scss \note path to package not individual file;
then in @import '../import/bootstrap-scss/assets/stylesheets/_bootstrap.scss';
Hope that will be it

**Comment by Adoyle2014** [comment]
What is the fix for working in windows.  I get an error saying 'ln' is not a recognized cmdlet, function, script file, or operable program.

**Comment by nikhilgoswami** [comment]
@Adoyle2014  For windows I guess you need to install bash terminal and run command on terminal

**Comment by derwaldgeist** [comment]
Stumbled upon this again. What I noticed in the meantime: this error quite often occurs if multiple SCSS libraries are using the same file names, like "variables.scss".
