### ISSUE TITLE
Error with @charset when importing Bulma

### ISSUE THREAD

**Issue by dhAlcojor** [Meteor-Community-Packages/meteor-scss#292]
- [ ] Feature request
- [x] Bug report
- [ ] Question

I'm just starting to use Meteor, so please, bear with me.

### Versions
fourseven:scss@4.12.0
meteor@1.9.3
meteor-base@1.4.0

### What I'm trying to do
I'm going through the tutorial while migrating the webapp I was creating with Next.js to Meteor. I'm trying to import Bulma, but I'm getting an error.

### The error
This is the error I'm getting:
```
error: Scss compiler error: Error: Invalid CSS after "@charset": expected 1 selector or at-rule, was '"utf-8"'
on line 1 of {}/node_modules/bulma/bulma
from line 1 of {}/client/main.scss
>> @charset "utf-8"
```

In my client/main.scss I'm importing bulma like this:
```
@import "{}/node_modules/bulma/bulma";
```

This is the code for that bulma.sass file:
```
@charset "utf-8"
/*! bulma.io v0.9.0 | MIT License | github.com/jgthms/bulma */
@import "sass/utilities/_all"
@import "sass/base/_all"
@import "sass/elements/_all"
@import "sass/form/_all"
@import "sass/components/_all"
@import "sass/grid/_all"
@import "sass/helpers/_all"
@import "sass/layout/_all"
```

As far as I can tell, all Bulma .sass files start with that `@charset "utf-8"` and it seems fourseven:scss doesn't understand the syntax.

**Comment by sebakerckhof** [comment]
Bulma is written in sass, which, as stated in the readme, is not supported by fourseven:scss (since it's not supported by libsass which we use).

**Comment by dhAlcojor** [comment]
No plans to make fourseven:scss compatible with Bulma? It's very popular...

**Comment by sebakerckhof** [comment]
No. Bulma uses the deprecated sass syntax which libsass does not support and will likely never support

**Comment by satyavh** [comment]
There seems to be something else going on here, because Vue Meteor compiles Bulma just fine using node-sass:
https://github.com/meteor-vue/vue-meteor/blob/master/packages/vue-sass/vue-sass.js

**Comment by satyavh** [comment]
Nothing to do with libsass, see #311

**Comment by sebastian-ruiz** [comment]
As a fix for this, you can use [bulma-scss](https://www.npmjs.com/package/bulma-scss) instead.
