### ISSUE TITLE
Can't find binary

### ISSUE THREAD

**Issue by sanyam-dhawan** [Meteor-Community-Packages/meteor-scss#293]
- [ ] Feature request
- [ ] Bug report 
- [x] Question

`meteor` version: 1.7.0.5

`fourseven:scss` version: 3.8.0

Errors prevented startup:                  
   
   While checking for fourseven:scss@3.8.0:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your
   platform.
   
=> Your application has errors. Waiting for file change.

  Where can i find those?

**Comment by sebakerckhof** [comment]
Please follow the compatibility table that's in the readme. Meteor 1.6+ needs fourseven:scss 4.12.0 or higher.
