### ISSUE TITLE
Remove prebuilding binaries a dependency for this package

### ISSUE THREAD

**Issue by RTSchriner** [Meteor-Community-Packages/meteor-scss#301]
- [x] Feature request
- [ ] Bug report
- [ ] Question

`meteor` version: 1.8

`fourseven:scss` version: 3.10.1

`OS` version: macOS Big Sur

I just had to install Xcode, an 11 GB application, to simply compile SCSS in Meteor... that seems like overkill. Please remove this dependency.

**Comment by sebakerckhof** [comment]
This is not possible as long as we can't transition to dart-sass. Since we use libsass, which requires the necessary node-gyp toolchains.
