### ISSUE TITLE
Node-Sass deprecated; recommendation is to switch to dart-sass

### ISSUE THREAD

**Issue by moberegger** [Meteor-Community-Packages/meteor-scss#305]
- [x] Feature request
- [ ] Bug report
- [ ] Question

`meteor` version: 2.2

`fourseven:scss` version: 4.12.0

According to the README, [`node-sass` has been deprecated](https://www.npmjs.com/package/node-sass), with the recommendation to switch to [dart-sass](https://sass-lang.com/dart-sass). I see that this has already been suggested #285, which was closed due to performance issues, but perhaps this new information changes things.

DartSass looks to be the primary supported compiler, and if it is something that is being adopted by other popular projects (for example, I stumbled across this when trying to use bootstrap 5 and ran into some issues with syntax that differed) then I think the switch should be given another consideration.

**Comment by moberegger** [comment]
Aaand I probably should have looked at open PRs... saw that there is a proposal already at https://github.com/Meteor-Community-Packages/meteor-scss/pull/296.

Didn't see another issue, so maybe this issue is worth keeping up for posterity, but feel free to close if you feel it adds unnecessary noise.

**Comment by sebakerckhof** [comment]
Closing as duplicate
