### ISSUE TITLE
Importing sass from scss throws error

### ISSUE THREAD

**Issue by satyavh** [Meteor-Community-Packages/meteor-scss#311]
- [ ]  Feature request
- [x] Bug report
- [ ] Question

It seems that this package only looks at the root file to determine whether to compile for scss or sass. For example this will throw during compilation:

_test.sass
```
@charset "utf-8"
```

index.scss
```
@import "_test";
```

It determines the compile method based on the root extension (in this case scss) and then tries to compile sass as scss. This is what's causing this issue #292 for example.

### Error

   While processing files with fourseven:scss (for target web.browser):
   /client/style/index.scss: Scss compiler error: Error: Invalid CSS after
   "@charset": expected selector, was '"utf-8"'
   on line 1 of {}/client/style/_test.sass
   from line 5 of {}/client/style/index.scss
   >> @charset "utf-8"
   ---------^

**Comment by sebakerckhof** [comment]
As mentioned in the readme, sass syntax is not supported because libsass does not support it

**Comment by satyavh** [comment]
Are you sure? 

https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-sass uses `node-sass` too and can handle mix of scss and sass just fine.
