### ISSUE TITLE
Can't deploy to heroku, failed to import ionic scss

### ISSUE THREAD

**Issue by weijian19391** [Meteor-Community-Packages/meteor-scss#99]
Hi! 

I've tried the setting stack solution (but i believe that the latest version of heroku doesn't require that setting already since they have deprecated the previous stack version https://devcenter.heroku.com/articles/cedar), and i'm still getting the error of 

```
remote: compiler error: file to import not found or unreadable:
remote: client/sass/ionic-sass/ionic
remote: Current dir: /tmp/build_08e0e2fa21f87670764444932920800a/client/sass/
remote: 
remote: 
remote: 
remote:  !     Push rejected, failed to compile Node.js app
```

what i've done: 
-git clone ionic-sass and ionicons-sass, put them in the same folder as app.scss. 

any help will be greatly appreciated!

**Comment by benjick** [comment]
Same error in Dokku, any takers?

**Comment by benjick** [comment]
@weijian19391 I took all the files from `myProject\.meteor\local\build\programs\server\assets\packages` and just copied them to another folder and set that in my .scss-file instead.

Now it looks like this:
```
$positive: #DE4F4F;

@import '.scss/meteoric_ionic-sass/ionic';
@import '.scss/meteoric_ionicons-sass/ionicons';
```

**Comment by lirbank** [comment]
If you use the [Horse buildpack](https://github.com/AdmitHub/meteor-buildpack-horse) you can set the `BUILDPACK_PRELAUNCH_METEOR` env and it will work, see the Horse readme.

**Comment by der-ede** [comment]
Hi there,

will this also work for Galaxy Deployments?
